### ISSUE TITLE
Firecracker 1.7.0

### ISSUE THREAD

**Issue by kanpov** [endjin/Firecracker.Management#53]
The SDK needs to be updated to version 1.7.0 of Firecracker

**Comment by HowardvanRooijen** [comment]
We'd be very interested to know what you're doing with the SDK - as we didn't think many .NET folks were playing with Firecracker.

**Comment by JamesDawson** [comment]
Hi @kanpov, thanks for the issue.  The above PR includes the version bump to 1.7.0 as well updating .NET version and other dependencies.

I think we can close the issue now, but let us know if you have any follow-up on this new version.  Thanks again!

**Comment by kanpov** [comment]
> We'd be very interested to know what you're doing with the SDK - as we didn't think many .NET folks were playing with Firecracker.

I'm using this autogenerated SDK as a reference to one I'm building myself with a wider scope: not just management, but booting jailed and normal VMs, support for CNI plugins, running commands through the TTY and so forth. I've got some of that working in my `FirecrackerSharp` repo.
